{% set version = "2.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-visnetwork
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/visNetwork_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/visNetwork/visNetwork_{{ version }}.tar.gz
  sha256: 47c99d42fc89e6ae929257b2648d998c5ffed60dff97ad7e47613f5a0c1ddc84

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr
  run:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-jsonlite
    - r-magrittr

test:
  commands:
    - $R -e "library('visNetwork')"           # [not win]
    - "\"%R%\" -e \"library('visNetwork')\""  # [win]

about:
  home: https://datastorm-open.github.io/visNetwork/
  license: MIT
  summary: Provides an R interface to the 'vis.js' JavaScript charting library. It allows an interactive visualization of networks.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: visNetwork
# Title: Network Visualization using 'vis.js' Library
# Version: 2.0.8
# Date: 2019-08-28
# Authors@R: c( person(family = "Almende B.V.", role = c("aut", "cph"), comment = "vis.js library in htmlwidgets/lib, http://visjs.org, http://www.almende.com/home"), person("Benoit", "Thieurmel", role = c("aut", "cre"), comment = "R interface", email = "benoit.thieurmel@datastorm.fr"), person(given = "Titouan", family = "Robert",  email = "titouan.robert@datastorm.fr", role = c("aut", "ctb")) )
# Maintainer: Benoit Thieurmel <benoit.thieurmel@datastorm.fr>
# Description: Provides an R interface to the 'vis.js' JavaScript charting library. It allows an interactive visualization of networks.
# BugReports: https://github.com/datastorm-open/visNetwork/issues
# URL: http://datastorm-open.github.io/visNetwork/
# Depends: R (>= 3.0)
# Imports: htmlwidgets, htmltools, jsonlite, magrittr, utils, methods, grDevices, stats
# License: MIT + file LICENSE
# Suggests: knitr, rmarkdown, webshot, igraph, rpart, shiny, shinyWidgets, colourpicker, sparkline, ggraph, tidygraph, flashClust
# VignetteBuilder: knitr, rmarkdown
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-08-28 12:31:13 UTC; Datastorm
# Author: Almende B.V. [aut, cph] (vis.js library in htmlwidgets/lib, http://visjs.org, http://www.almende.com/home), Benoit Thieurmel [aut, cre] (R interface), Titouan Robert [aut, ctb]
# Repository: CRAN
# Date/Publication: 2019-08-28 13:40:03 UTC
