{% set version = '2.0.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-visnetwork
  version: {{ version|replace("-", "_") }}

source:
  fn: visNetwork_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/visNetwork_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/visNetwork/visNetwork_{{ version }}.tar.gz
  sha256: bc2e75cf4cc1410d8eb528a38870666117e674f1b9ba5fa1ff769b8ab2e2462f

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-htmlwidgets
    - r-htmltools
    - r-jsonlite
    - r-magrittr
  run:
    - r-base
    - r-htmlwidgets
    - r-htmltools
    - r-jsonlite
    - r-magrittr

test:
  commands:
    - $R -e "library('visNetwork')"  # [not win]
    - "\"%R%\" -e \"library('visNetwork')\""  # [win]

about:
  home: https://github.com/datastorm-open/visNetwork
  license: MIT
  summary: Provides an R interface to the 'vis.js' JavaScript charting library. It allows an
    interactive visualization of networks.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
