# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GOq4CkEH4D9E6WC0zKA79xd99Sw3JMH02oDPt/fqPEOq8XWLV+hxFJB4TobRZ3phPUZoBNKy2Iz4tUULpG8p18BCaKI0onmjLDLaeuEhnMWPgIhuuRDXVi/fNOXW03JqlC3AZkEmNxEm4Yqz5rCkOD01DPzuWFteC5ErJBaa8rHIvHcZMpYl9L7E52olXziMZjEENdvReaf8m+uWlG3YsEbWw9pAyhKMC8FDUSgpseQxhKEMIR/mXlRii9SZv4iEkGaKMRcxMor83S+XtXM4Sf9cVkEPubQ3OXTZ2GFyMZecWoslrJd/sbVERNs/3Sci2Am5W6BDWhalKSRbBYmaTDxOD2LwkzZu6fVjsv4Y/R8zRJtomokVYf7A9x8v0fedRLwg8f3Bmz5/l+JsHl0hT5HltnAmQfYDY/NTOat+kZJVoG7FmsXGbXynZChKYEo93Se2YJQpi8MyzQB2fNbJLiiOb1W3IoV79kFHsf2uN4xURQ/SlM3fuj3Fkseh7gqldkDBWuZPoctEYYqEw+oMQNq2R4HImWAjBar7WE++Pnpo7TxePIixt6W3jz7Z7m5Shfa1/fZQsDKMRT1jfX5W/0GTLJm8z3IYt3OMu+MJFuk2IyvRDi39VeLZbMTrvMeQLij+g2MEgSmjL696xxT9vfIRIewGt6xsAggzyIcBKGc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
